const app = Vue.createApp({});
import navbar  from "./src/componentes/navbar.js";
import banner from "./src/componentes/banner.js";
import about from "./src/componentes/about.js";
import chapters from "./src/componentes/chapters.js";
import support from "./src/componentes/support.js";
app.component("navbar", navbar);
app.component("banner", banner);
app.component("about", about);
app.component("chapters", chapters);
app.component("support", support);
app.mount("#app");
